name: Deploy Ubuntu

on:
    push:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Installer des dépendances test
              run: apt update && apt install -y curl mysql-client

            - name: Exécuter un script bash
              run: echo "Hello depuis un conteneur Ubuntu!"
