name: Deploiment Ubuntu
# se déclanche sur :
on:
    push:
        branches: [main]
    pull_request:
        branches: [main]
# liste des jobs à exécuter
jobs:
    nom-job:
        # démarre une image ubuntun
        runs-on: ubuntu-latest
