name: Setup MySQL 8

on:
    push:
        branches:
            - main

jobs:
    setup-mysql:
        runs-on: ubuntu-latest

        services:
            mysql:
                image: mysql:8
                env:
                    MYSQL_ALLOW_EMPTY_PASSWORD: "no"
                    MYSQL_ROOT_PASSWORD: root
                    MYSQL_DATABASE: testdb
                    MYSQL_USER: Flo
                    MYSQL_PASSWORD: AZERTY1234
                ports:
                    - 3306:3306
                options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

        steps:
            - name: Vérifier la connexion MySQL
              run: |
                  mysql --host=127.0.0.1 --user=Flo --password=AZERTY1234 --execute="SHOW DATABASES;"
