name: Setup MySQL 8

on:
    push:
        branches:
            - main

jobs:
    setup-mysql:
        runs-on: ubuntu-latest

        services:
            mysql:
                image: mysql:8
                env:
                    MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
                    MYSQL_ROOT_PASSWORD:
                    MYSQL_DATABASE: testdb
                    MYSQL_USER: root
                    MYSQL_PASSWORD:
                ports:
                    - 3307:3307
                options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

        steps:
            - name: Installer MySQL client
              run: sudo apt update && sudo apt install -y mysql-client

            - name: Vérifier la connexion MySQL
              run: |
                  mysql --host=127.0.0.1:3307 --user=root --password= --execute="SHOW DATABASES;"
